Coursera/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import  handler404, handler403, handler500

handler404 = 'courses.views.view_404'
handler500 = 'courses.views.view_500'
handler403 = 'courses.views.view_403'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls',namespace='courses')),
    path('', include('blog.urls',namespace='blogs')),
    path('', include('memberships.urls',namespace='memberships')),
    path('', include('users.urls',namespace='users')),
    path('accounts/', include('allauth.urls')),
   
    
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .import views

app_name = 'blogs'

urlpatterns = [
     
    path("blog/",views.bloghome,name='bloghome'),
    path('blogs/<slug>/',views.blogpost,name='blogpost'),
   


]

courses/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required



from courses.views import HomeView,AboutView,ContactView,CourseListView, CourseDetailView,LessonDetailView, SearchView, krijo_klase, krijo_lende, krijo_mesim

app_name = 'courses'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView, name='contact'),
    path('courses/<int:category>', CourseListView, name='course_list'),
    path('courses/<slug>/', login_required(CourseDetailView.as_view()), name='course_detail'),
    path('courses/<course_slug>/<lesson_slug>/', login_required(LessonDetailView.as_view()), name='lesson_detail'),
    path('search/', SearchView, name='kerko_kurs'),
    path('krijo/klase', krijo_klase, name='krijo_klase'),
    path('krijo/lende', krijo_lende, name='krijo_lende'),
    path('krijo/mesim', krijo_mesim, name='krijo_mesim'),
   

]

users/urls.py
from django.urls import path

from users.views import Profile, kerkesa

app_name = 'users'

urlpatterns = [
    path('profile/', Profile, name='profile'),
    path('kerkesa/', kerkesa, name='kerkesa'),
  

]

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<!-- Page info -->
<div class="page-info-section set-bg" data-setbg="{% static 'webuni/img/page-bg/4.jpg' %}">
  <div class="container">
    <div class="site-breadcrumb">
      <a href="/">Home</a>
      <span>Course</span>
    </div>
  </div>
</div>
<!-- Page info end -->


<section class="about-us py-5 " id="about-us">
    <div class="container mt-5">
	<div class="row">
		<div class="col-md-6">
		    <h1 class='text-primary'>AshuTechStudy</h1>
		    <h2>This Website is Learning base Platform</h2>
			<hr>
			<h1>Our mission</h1>
			<p>To help you learn the skills you need to achieve your full potential.</p>
			<h3>About</h3>
		    <p>AshuTechStudy is a leading  learning platform that helps anyone learn software, technology and creative skills to achieve personal and professional goals. Through individual, corporate, academic and government subscriptions, members have access to the Course and video library of engaging, top-quality courses learn in Our website.

				 AshuTechStudy has helped all  students, leaders, project managers—anyone in any role—develop software, creative, and business skills.AshuTechStudy all service Provided in Learning Field. With tutorials, AshuTechStudy is a global platform for success..</p>
		    <p>At AshuTechStudy, we’ve seen again and again how the seemingly simple act of creating can be a force for growth, change, and discovery in people’s lives. We want to inspire and multiply the kind of creative exploration that furthers expression, learning and application.</p>
		    <button type="button" class="btn btn-primary">Let's Know More</button>

		</div>
		<div class="col-md-6">
		    <img src="http://themebubble.com/demo/marketingpro/wp-content/uploads/2016/10/seo-slide.png "alt="">
		</div>
	</div>
</div>
</section>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>AshuTechStudy - Home </title>
	<meta charset="UTF-8">
	<meta name="description" content="WebUni Education Template">
	<meta name="keywords" content="webuni, education, creative, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Favicon -->
	<link href="{% static 'webuni/img/favicon.png' %}" rel="shortcut icon"/>

	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,500,500i,600,600i,700,700i,800,800i" rel="stylesheet">

	<!-- Stylesheets -->
	<link rel="stylesheet" href="{% static 'webuni/css/bootstrap.min.css'%}"/>
	<link rel="stylesheet" href="{% static 'webuni/css/font-awesome.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'webuni/css/owl.carousel.css' %}"/>
	<link rel="stylesheet" href="{% static 'webuni/css/style.css'%}"/>
	<link rel="stylesheet" href="{% static 'webuni/css/freelancer.css'%}"/>
	<link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />


	<!--[if lt IE 9]>
	  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>
<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<nav class="navbar navbar-expand-lg bg-secondary text-uppercase" id="mainNav">
		<div class="container">
		  <a class="navbar-brand js-scroll-trigger" href="/"><img src="{% static 'webuni/img/logo7.png' %}" height="50px" alt=""><b style="color: rgb(250, 125, 67);"></b></a>
		  <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
			Menu
	
		  </button>
		  <div class="collapse navbar-collapse" id="navbarResponsive">
			<ul class="navbar-nav ml-auto">
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:home' %}">Home</a>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<li class="nav-item mx-0 mx-lg-1">
					<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="/#kurset">Course</a>
				  </li>
			  </li>


			  
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:contact' %}">Contact</a>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:about' %}">About</a>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'blogs:bloghome' %}">Blog</a>
			  </li>
			  
			  
			  {% if request.user.is_authenticated %}
			  
			  <div class="dropdown show">
				<a class=" dropdown-toggle nav-link py-3 px-0 px-lg-3 rounded js-scroll-triggeraa" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					{{request.user.username}}
				</a>
			  
				<div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
				  <!-- <a class="dropdown-item" href="{% url 'users:profile' %}">Profili</a> -->
				  <a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a>
				</div>
			  </div>
			  {% else %}
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="active nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'account_login' %}">Login</a>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="active nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'account_signup' %}">Registration</a>
			  </li>
              {% endif %}
			</ul>
		  </div>
		</div>
	  </nav>

{% include 'inc/messages.html' %}
{% block content %}

{% endblock content %}

{% if request.user.is_authenticated %}
{% else %}
	<!-- banner section -->
	<section class="banner-section spad">
		<div class="container">
			<div class="section-title mb-0 pb-2">
				<h2>Learning Hare Registration First</h2>
				<p>Get your programming career started with these free video courses. Source code is available with all the videos for your better experience:Some of the latest coding information compiled as coding articles. Keep your programming knowledge up to date with our coding articles. </p>
			</div>
			<div class="text-center pt-5">
				<a href="{% url 'account_signup' %}" class="site-btn">Registration Hare</a>
			</div>
		</div>
	</section>
	<!-- banner section end -->
{% endif %}


	<!-- footer section -->
	<footer class="footer-section spad pb-0 bg-dark">
		<div class="footer-top ">
			<div class="footer-warp">
				<div class="row ">
					<div class="widget-item">
						<h4><b class=text-white>Contact Me</b></h4>
						<ul class="contact-list">
							<li><b class=text-white>ashutechstudy@gmail.com</b></li>
							<li><b class=text-white>aashuk012@gmail.com</b></li>
						</ul>
					</div>
					<div class="widget-item">
						<h4><b class=text-white>Course Category</b></h4>
						<ul>
							<li><a href="/#kurset"><b class=text-white>Learn All Courses</b></a></li>
							<li><a href="{% url 'courses:about' %}"><b class=text-white>About</b></a></li>
							<li><a href="{% url 'blogs:bloghome' %}"><b class=text-white>Blog</b></a></li>
							<li><a href=""><b class=text-white>Web Develapment</b></a></li>
							<li><a href=""><b class=text-white>Interview Informaction,etc</b></a></li>
						</ul>
					</div>
					<div class="widget-item">
						<h4><b class=text-white>Informaction</b></h4>
						<ul>
							<li><a href="{% url 'courses:contact' %}"><b class=text-white>Contact</b></a></li>
							<li><a href="{% url 'courses:about' %}"><b class=text-white>About</b></a></li>
							<li><a href="{% url 'blogs:bloghome' %}"><b class=text-white>Blog</b></a></li>
							
						</ul>
					</div>
					<div class="widget-item">
						<h4><b class=text-white>Social Media</b></h4>
						<ul>
						<li><a href="https://in.pinterest.com/aashuk012/"><i class="fa fa-pinterest fa-2x icon-cog"></i></a></li>
						<li><a href="https://www.facebook.com/AshuKashyap-112885700424232"><i class="fa fa-facebook fa-2x"></i></a></li>
						<li><a href="https://twitter.com/aashukashyap6"><i class="fa fa-twitter fa-2x"></i></a></li>
						<li><a href="https://www.linkedin.com/in/ashu-kashyap-174505136/"><i class="fa fa-linkedin fa-2x"></i></a></li>
							  
						</ul>
					</div>
					<div class="widget-item">
						<h4><b class= "text-white">Email Sand</b></h4>
						<form class="footer-newslatter">
							<input type="email" placeholder="E-mail">
							<button class="site-btn"><b class="text-white">Submit</b></button>
							<p><b class=text-white>*Sand Any information </b></p>
						</form>
					</div>
				</div>
			</div>
		</div>
		<div class="footer-bottom bg-dark">
			<div class="footer-warp">
				<ul class="footer-menu">
					<li><a href="#"><b class=text-white>Terms & Conditions</b></a></li>
					<li><a href="{% url 'account_signup' %}"><b class=text-white>Register</b></a></li>
					<li><a href="#"><b class=text-white>Privacy</b></a></li>
				</ul>
				<div class="text-white">
	<b>Copyright &copy; AshuTechStudy <script>document.write(new Date().getFullYear());</script> All rights reserved.</b>
</div>
			</div>
		</div>
	</footer>
	<!-- footer section end -->


	<!--====== Javascripts & Jquery ======-->
	<script src="{% static 'webuni/js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'webuni/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'webuni/js/mixitup.min.js' %}"></script>
	<script src="{% static 'webuni/js/circle-progress.min.js' %}"></script>
	<script src="{% static 'webuni/js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'webuni/js/main.js' %}"></script>
	<script src="{% static 'webuni/js/freelancer.js' %}"></script>
	<script src="https://unpkg.com/aos@next/dist/aos.js"></script>
  <script>
    AOS.init();
  </script>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<!-- Page info -->
<div class="page-info-section set-bg" data-setbg="{% static 'webuni/img/page-bg/4.jpg' %}">
  <div class="container">
    <div class="site-breadcrumb">
      <a href="#">Home</a>
      <span>Contact</span>
    </div>
  </div>
</div>
<!-- Page info end -->


<!-- search section -->
<section class="search-section ss-other-page">
  <div class="container">
    <div class="search-warp">
      <div class="section-title text-white">
        <h2><span>Search your course</span></h2>
      </div>
      <div class="row">
        <div class="col-lg-10 offset-lg-1">
          <!-- search form -->
          <form class="course-search-form">
            <input type="text" placeholder="Course">
            <input type="text" class="last-m" placeholder="Category">
            <button class="site-btn btn-dark">Search Couse</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- search section end -->



<!-- Page -->
<section class="contact-page spad pb-0">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <div class="contact-form-warp">
          <div class="section-title text-white text-left">
            <h2>Get in Touch</h2>
            <p> Contact AshuTechStudy For Any Informaction </p>
          </div>
          <form method="post" action="/contact/" class="contact-form">{% csrf_token %}
            <input type="text" name="name" placeholder="Your Name" required>
            <input type="text" name="email" placeholder="Your E-mail" required>
            <input type="text" name="subject" placeholder="Subject" required>
            <textarea  name="message" placeholder="Message" required></textarea>
            <button type="submit" class="site-btn">Sent Message</button>
          </form>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="contact-info-area">
          <div class="section-title text-left p-0">
            <h2>Contact Info</h2>
            <p>Contact For Any Informaction.</p>
          </div>
          <div class="phone-number">
            <span>Direct Line</span>
            <h2>+9148091356855</h2>
          </div>
          <ul class="contact-list">
            <li>Saharanpur <br>UttarPardesh</li>
            <li>+9148091356855</li>
            <li>ashutechstudy@gmail.com</li>
          </ul>
          <div class="social-links">
            <a href="https://in.pinterest.com/aashuk012/"><i class="fa fa-pinterest fa-2x"></i></a>
            <a href="https://www.facebook.com/AshuKashyap-112885700424232"><i class="fa fa-facebook fa-2x"></i></a>
            <a href="https://twitter.com/aashukashyap6"><i class="fa fa-twitter fa-2x"></i></a>
            <a href="https://www.linkedin.com/in/ashu-kashyap-174505136/"><i class="fa fa-linkedin fa-2x"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Page end -->

{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<!-- Hero section -->

<section class="hero-section set-bg" data-setbg="{% static 'webuni/img/css.jpg'%}">
    <div class="container-fluid">
        <div class="hero-text text-white">


            {% if request.user.is_authenticated %}
            <h2>Welcome {% if request.user.profile.is_teacher == True %}
                To
                {% endif %} {{ request.user.username|capfirst }}


            </h2>
            {% else %}
            <h2>Welcome AshuTechStudy</h2>

            {% endif %}
            <p>Confused on which course to take? I have got you covered. Browse courses and find out
                the best course for you. Its free!<br>AshuTechStudy is my attempt to teach basics and those coding
                techniques to people in short time which took me ages to learn.</p>
        </div>
        <div class="row">
            <div class="col-lg-10 offset-lg-1">
                <form method="post" action="{% url 'courses:kerko_kurs' %}" class="intro-newslatter" style="margin-top: -85px;"> {% csrf_token %}
                    <input name="search" type="text" placeholder="Search Course">
                    <button type="submit" class="site-btn">Search Course</button>
                </form>
            </div>
        </div>

    </div>
</section>
<!-- Hero section end -->

<!-- categories section -->
<section class="categories-section spad">
    <div class="container">
        <div class="section-title">
            <h2 id="kurset">Learn all Courses</h2>
            <p>Some of the latest coding information compiled as coding articles. Keep your
                programming knowledge up to date with our coding articles.</p>
        </div>
        <div class="row">
            {% for cat in category %}
            <!-- categorie -->
            <div data-aos="zoom-in" class="col-lg-4 col-md-6">
                <div class="categorie-item">
                    <div class="ci-thumb set-bg" data-setbg="{{ cat.imazhi.url }}"></div>
                        <div class="ci-text">

                            <h5>{{cat.titulli|capfirst }}</h5>

                            <p>{{ cat.pershkrimi|capfirst }}</p>
                            <span><a class="btn btn-success" href="/courses/{{ cat.id }}">View Course</a></span>
                        </div>
                    </div>
                </div>

            {% endfor %}
        </div>
    </div>
</section>
<!-- categories section end -->
{% if request.user.is_authenticated %}
{% else %}
<section class="course-section spad">
    <div class="container">
        <div class="section-title mb-0">
            <h2>Introduction Video</h2>

        </div>
    </div>
    <div class="course-warp">
        <div class="row course-items-area">
            <!-- course -->
            <div class="mix col-lg-3 col-md-4 col-sm-6 finance">
                <div class="course-item">
                    <div class="course-thumb set-bg" data-setbg="{% static 'webuni/img/courses/4.jpg' %}">
                        <iframe width="100%" height="290" src="https://www.youtube.com/embed/ZrxO4qegCUU?controls=0"
                                frameborder="0" controls allowfullscreen></iframe>

                    </div>
                    <div class="course-info">
                        <div class="course-text">
                            <h5>knowledge Base</h5>
                            <p>programming</p>
                            <div class="students">view</div>

                        </div>
                        <div class="course-author">
                            <div class="ca-pic set-bg" data-setbg="{% static 'webuni/img/authors/4.jpg' %}">
                                <p>admin</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- course -->
            <div class="mix col-lg-3 col-md-4 col-sm-6 design">
                <div class="course-item">
                    <div class="course-thumb set-bg" data-setbg="{% static 'webuni/img/courses/4.jpg' %}">
                        <iframe width="100%" height="290" src="https://www.youtube.com/embed/mNJ06S60B9k?controls=0"
                                frameborder="0"
                                allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                                allowfullscreen></iframe>
                    </div>
                    <div class="course-info">
                        <div class="course-text">
                            <h5>Programmar</h5>
                            <p>Learn</p>
                            <div class="students">View</div>
                        </div>
                        <div class="course-author">
                            <div class="ca-pic set-bg" data-setbg="{% static 'webuni/img/authors/4.jpg' %}"></div>
                            <p>Admin</p>
                        </div>
                    </div>
                </div>
            </div>
            <!-- course -->
            <div class="mix col-lg-3 col-md-4 col-sm-6 web">
                <div class="course-item">
                    <div class="course-thumb set-bg" data-setbg="{% static 'webuni/img/courses/4.jpg' %}">
                        <iframe width="100%" height="290" src="https://www.youtube.com/embed/wclSLQEvk3k?controls=0"
                                frameborder="0"
                                allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                                allowfullscreen></iframe>
                    </div>
                    <div class="course-info">
                        <div class="course-text">
                            <h5>Job Interview</h5>
                            <p>Learn</p>
                            <div class="students">View</div>
                        </div>
                        <div class="course-author">
                            <div class="ca-pic set-bg" data-setbg="{% static 'webuni/img/authors/4.jpg' %}"></div>
                            <p>Admin</p>
                        </div>
                    </div>
                </div>
            </div>
            <!-- course -->
            <div class="mix col-lg-3 col-md-4 col-sm-6 photo">
                <div class="course-item">
                    <div class="course-thumb set-bg" data-setbg="{% static 'webuni/img/courses/4.jpg' %}">
                        <iframe width="100%" height="290" src="https://www.youtube.com/embed/LQFsEwcCO1E?controls=0"
                                frameborder="0"
                                allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                                allowfullscreen></iframe>
                    </div>
                    <div class="course-info">
                        <div class="course-text">
                            <h5>Web developer</h5>
                            <p>Learn</p>
                            <div class="students">View</div>
                        </div>
                        <div class="course-author">
                            <div class="ca-pic set-bg" data-setbg="{% static 'webuni/img/authors/4.jpg' %}"></div>
                            <p>Admin</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endif %}
<!-- course section end -->

<div class="card-columns">
    {% for i in latest %}
    
    <div class="card" style="width: 20rem;">
      <img src="/media/{{i.photo}}" class="card-img-top" height="200px"  alt="...">
      <div class="card-body">
        <a href="{% url 'blogs:blogpost' i.slug %}" class="card-title"><h5>{{i.title}}</h5></a>
        <div class="text-justify">
        <p class="card-text">{{i.content|truncatechars:100|safe}}.</p>
      </div>
        <a href="{% url 'blogs:blogpost' i.slug %}" class="btn btn-primary">Contune Reading</a>
      </div>
    </div>
    {% endfor %}
  </div>


{% if request.user.is_authenticated %}


<div class="container">
    <h1 class="text-center">Add Your Course </h1><br>
    <p class="text-center">Add Your Subject and become a member of the AshuTechStudy Team you are uploade all categorie
        Course this website Give all permission this Platform</p>

    <div data-aos="fade-right" class="row mt-4 mb-4 bg-light">
        <div class="col-md-4 text-center">
            <h3 class="p-4">Add Your Category Course </h3>
            <a href="{% url 'courses:krijo_klase' %}" class="btn btn-outline-primary m-4">Submit Course</a>
        </div>
        <div class="col-md-8">
            <img class="img-fluid w-100" src="{% static 'webuni/img/categories/4.jpg' %}" alt="">
        </div>
    </div>

    <div data-aos="fade-left" class="row mt-4 mb-4 bg-light">
        <div class="col-md-8">
            <img class="img-fluid w-100" src="{% static 'webuni/img/categories/2.jpg' %}" alt="">
        </div>

        <div class="col-md-4 text-center">
            <h3 class="p-4">Add Category Subject </h3>
            <a href="{% url 'courses:krijo_lende' %}" class="btn btn-outline-primary m-4">Submit Subject</a>
        </div>
    </div>

    <div data-aos="fade-right" class="row mt-4 mb-4 bg-light">
        <div class="col-md-4 text-center">
            <h3 class="p-4">Add All Subject Lesson.</h3>
            <a href="{% url 'courses:krijo_mesim' %}" class="btn btn-outline-primary m-4">Submit Lesson</a>
        </div>
        <div class="col-md-8">
            <img class="img-fluid w-100" src="{% static 'webuni/img/categories/1.jpg' %}" alt="">
        </div>
    </div>
</div>

{% else %}

<section data-aos="zoom-in" class="signup-section spad">
    <div class="signup-bg set-bg" data-setbg="{% static 'webuni/img/css.jpg' %}"></div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6">
                <div class="signup-warp">
                    <div class="section-title text-white text-left">
                        <h2>Contact The Teacher</h2>
                        <p>Contact me add Your Course.</p>
                    </div>
                    <!-- signup form  -->
                    {% if message %}
                    <div class="alert alert-{{cls}}">{{message}}</div>

                    {% endif %}
                    <form action="/kerkesa/" method="post" class="signup-form">{% csrf_token %}
                        <input type="text" placeholder="Name" name="name">
                        <input type="text" placeholder="Email" name="e-mail">
                        <input type="text" placeholder="Number " name="phone">
                        <button class="site-btn">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
 
</div>
</section>



{% endif %}
 <!-- signup section end  -->
 

{% endblock content %}